name: Export & Deploy — WEB CORE

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

env:
  NODE_VERSION: '22'
  NODE_ENV: development
  # База строго под Project Pages (имя репозитория)
  VITE_BASE: "/${{ github.event.repository.name }}/"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run typecheck

      - name: Run tests (Vitest if any specs)
        if: ${{ hashFiles('**/*.spec.ts') != '' }}
        run: npx -y vitest run --passWithNoTests

      - name: Build & export (redacted)
        run: npx -y tsx tools/export.ts

      - name: Merge redacted data into site bundle
        run: |
          mkdir -p export/site/data
          rsync -a export/data/ export/site/data/ || true

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: export/site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

