name: Export & Deploy - WEB CORE

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - run: npm run validate:content

      # Экспорт в export/site: сборка + 404.html + .nojekyll
      - run: npm run export
        env:
          GITHUB_ACTIONS: 'true'

      - uses: actions/upload-pages-artifact@v3
        with:
          path: export/site

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
